name: "Dienstplan OCR"
version: "1.0"
slug: "dienstplan_ocr"
description: "Erkennt fotografierte Dienstpläne und erstellt .ics-Dateien"
arch:
  - aarch64
  - armv7
  - amd64
startup: application
boot: auto
init: false
homeassistant_api: false
host_network: false
options: {}
schema: {}
