name: "Dienstplan OCR"
version: "1.0"
slug: dienstplan_ocr
description: "Erkennt fotografierte Dienstpläne und erstellt .ics-Dateien"
startup: application
boot: auto
init: false
homeassistant: 2023.0.0
arch:
  - aarch64
  - armv7
  - amd64
host_network: false
options: {}
schema: {}
image: "local/dienstplan_ocr"
map:
  - config:rw
