name: "Dienstplan OCR"
version: "1.0"
slug: dienstplan_ocr
description: "Erkennt fotografierte Dienstpläne und erstellt .ics-Dateien"
startup: application
boot: auto
init: false
homeassistant: 2023.0.0
arch:
  - aarch64
  - armv7
  - amd64
host_network: false
options: {}
schema: {}
map:
  - config:rw
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.13"
  armv7: "ghcr.io/home-assistant/armv7-base:3.13"
  amd64: "ghcr.io/home-assistant/amd64-base:3.13"
